### ISSUE TITLE
Mover apply para um stage separado

### ISSUE THREAD

**Issue by joaoheytor** [toolbox-playground/terraform-sdesocds#22]
É necessário criar um novo stage para o comando apply da pipeline:

```yaml
      - name:  Aplicação (Terraform Apply) - Requer Aprovação
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
```
